<#
.SYNOPSIS
    Sign latest.json with the private key before uploading to the server.
    The client app verifies this signature to prevent tampering.

.PARAMETER LatestJsonPath
    Path to latest.json to sign.

.PARAMETER PrivateKeyFile
    Path to private_key.txt (generated by generate-keys.ps1).

.EXAMPLE
    .\sign-latest.ps1 -LatestJsonPath ..\TLAHStudio.Installer\latest.json -PrivateKeyFile .\private_key.txt
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$LatestJsonPath,

    [Parameter(Mandatory=$true)]
    [string]$PrivateKeyFile
)

if (-not (Test-Path $LatestJsonPath)) {
    Write-Error "latest.json not found: $LatestJsonPath"
    exit 1
}
if (-not (Test-Path $PrivateKeyFile)) {
    Write-Error "Private key not found: $PrivateKeyFile"
    exit 1
}

$data = Get-Content -Path $LatestJsonPath -Raw
$privateKeyBase64 = Get-Content -Path $PrivateKeyFile -Raw

$ecdsa = [System.Security.Cryptography.ECDsa]::Create()
$ecdsa.ImportPkcs8PrivateKey([Convert]::FromBase64String($privateKeyBase64), [ref]$null)
$dataBytes = [System.Text.Encoding]::UTF8.GetBytes($data)
$signature = $ecdsa.SignData($dataBytes, [System.Security.Cryptography.HashAlgorithmName]::SHA256)
$signatureBase64 = [Convert]::ToBase64String($signature)

# Write .sig file
$sigPath = "$LatestJsonPath.sig"
$signatureBase64 | Out-File -FilePath $sigPath -Encoding ascii -NoNewline

Write-Host "Signed: $LatestJsonPath" -ForegroundColor Green
Write-Host "Signature: $sigPath"
Write-Host "Upload BOTH files to the server."
